/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAboutRouteImport } from './routes/app/about'
import { Route as AppBonusRouteImport } from './routes/app/bonus'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppMissionsRouteImport } from './routes/app/missions'
import { Route as AppNetworkExtractRouteImport } from './routes/app/network-extract'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppRechargeRouteImport } from './routes/app/recharge'
import { Route as AppRechargeHistoryRouteImport } from './routes/app/recharge-history'
import { Route as AppReferralRouteImport } from './routes/app/referral'
import { Route as AppSecurityRouteImport } from './routes/app/security'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as AppWithdrawHistoryRouteImport } from './routes/app/withdraw-history'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppBonusRoute = AppBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkExtractRoute = AppNetworkExtractRouteImport.update({
  id: '/network-extract',
  path: '/network-extract',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRechargeRoute = AppRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AppRoute,
} as any)
const AppRechargeHistoryRoute = AppRechargeHistoryRouteImport.update({
  id: '/recharge-history',
  path: '/recharge-history',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawHistoryRoute = AppWithdrawHistoryRouteImport.update({
  id: '/withdraw-history',
  path: '/withdraw-history',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/bonus': typeof AppBonusRoute
  '/app/history': typeof AppHistoryRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/network-extract': typeof AppNetworkExtractRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recharge': typeof AppRechargeRoute
  '/app/recharge-history': typeof AppRechargeHistoryRoute
  '/app/referral': typeof AppReferralRoute
  '/app/security': typeof AppSecurityRoute
  '/app/support': typeof AppSupportRoute
  '/app/team': typeof AppTeamRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdraw-history': typeof AppWithdrawHistoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/about': typeof AppAboutRoute
  '/app/bonus': typeof AppBonusRoute
  '/app/history': typeof AppHistoryRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/network-extract': typeof AppNetworkExtractRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recharge': typeof AppRechargeRoute
  '/app/recharge-history': typeof AppRechargeHistoryRoute
  '/app/referral': typeof AppReferralRoute
  '/app/security': typeof AppSecurityRoute
  '/app/support': typeof AppSupportRoute
  '/app/team': typeof AppTeamRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdraw-history': typeof AppWithdrawHistoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/bonus': typeof AppBonusRoute
  '/app/history': typeof AppHistoryRoute
  '/app/missions': typeof AppMissionsRoute
  '/app/network-extract': typeof AppNetworkExtractRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recharge': typeof AppRechargeRoute
  '/app/recharge-history': typeof AppRechargeHistoryRoute
  '/app/referral': typeof AppReferralRoute
  '/app/security': typeof AppSecurityRoute
  '/app/support': typeof AppSupportRoute
  '/app/team': typeof AppTeamRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdraw-history': typeof AppWithdrawHistoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/about'
    | '/app/bonus'
    | '/app/history'
    | '/app/missions'
    | '/app/network-extract'
    | '/app/products'
    | '/app/profile'
    | '/app/recharge'
    | '/app/recharge-history'
    | '/app/referral'
    | '/app/security'
    | '/app/support'
    | '/app/team'
    | '/app/withdraw'
    | '/app/withdraw-history'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/about'
    | '/app/bonus'
    | '/app/history'
    | '/app/missions'
    | '/app/network-extract'
    | '/app/products'
    | '/app/profile'
    | '/app/recharge'
    | '/app/recharge-history'
    | '/app/referral'
    | '/app/security'
    | '/app/support'
    | '/app/team'
    | '/app/withdraw'
    | '/app/withdraw-history'
    | '/auth/login'
    | '/auth/register'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/about'
    | '/app/bonus'
    | '/app/history'
    | '/app/missions'
    | '/app/network-extract'
    | '/app/products'
    | '/app/profile'
    | '/app/recharge'
    | '/app/recharge-history'
    | '/app/referral'
    | '/app/security'
    | '/app/support'
    | '/app/team'
    | '/app/withdraw'
    | '/app/withdraw-history'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bonus': {
      id: '/app/bonus'
      path: '/bonus'
      fullPath: '/app/bonus'
      preLoaderRoute: typeof AppBonusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/missions': {
      id: '/app/missions'
      path: '/missions'
      fullPath: '/app/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network-extract': {
      id: '/app/network-extract'
      path: '/network-extract'
      fullPath: '/app/network-extract'
      preLoaderRoute: typeof AppNetworkExtractRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recharge': {
      id: '/app/recharge'
      path: '/recharge'
      fullPath: '/app/recharge'
      preLoaderRoute: typeof AppRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recharge-history': {
      id: '/app/recharge-history'
      path: '/recharge-history'
      fullPath: '/app/recharge-history'
      preLoaderRoute: typeof AppRechargeHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw-history': {
      id: '/app/withdraw-history'
      path: '/withdraw-history'
      fullPath: '/app/withdraw-history'
      preLoaderRoute: typeof AppWithdrawHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppBonusRoute: typeof AppBonusRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppNetworkExtractRoute: typeof AppNetworkExtractRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRechargeRoute: typeof AppRechargeRoute
  AppRechargeHistoryRoute: typeof AppRechargeHistoryRoute
  AppReferralRoute: typeof AppReferralRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppWithdrawHistoryRoute: typeof AppWithdrawHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppBonusRoute: AppBonusRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppNetworkExtractRoute: AppNetworkExtractRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRechargeRoute: AppRechargeRoute,
  AppRechargeHistoryRoute: AppRechargeHistoryRoute,
  AppReferralRoute: AppReferralRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSupportRoute: AppSupportRoute,
  AppTeamRoute: AppTeamRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppWithdrawHistoryRoute: AppWithdrawHistoryRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
