// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env["DATABASE_URL"]?.trim() ?? "";

/** Build/deploy na Vercel: só PostgreSQL via DATABASE_URL — nunca file: / SQLite. */
if (process.env.VERCEL) {
  if (!dbUrl || dbUrl.startsWith("file:")) {
    throw new Error(
      "DATABASE_URL na Vercel deve ser uma connection string PostgreSQL. Não use file: nem SQLite."
    );
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: dbUrl,
  },
});
