ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "withdrawBlockEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "withdrawBlockStartHour" INTEGER NOT NULL DEFAULT 22;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "withdrawBlockEndHour" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "withdrawDailyLimitPerUser" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlatformSettings" ADD COLUMN IF NOT EXISTS "withdrawDailyLimitPlatform" INTEGER NOT NULL DEFAULT 0;
